sudo: true

language: python

services:
  - docker

addons:
  apt:
    packages:
    - qemu-user-static


before_install:
  - docker build -t chukysoria/pyspotify-connect .

script:
  - docker run chukysoria/pyspotify-connect coverage run --source=spotifyconnect tox

after_succes:
  - docker run chukysoria/pyspotify-connect coveralls
 